# packages in environment at /home/thunder/anaconda3/envs/hyperopt-presentation:
#
_license                  1.1                      py34_0  
abstract-rendering        0.5.1                np19py34_0  
alabaster                 0.7.3                    py34_0  
anaconda                  2.3.0                np19py34_0  
argcomplete               0.8.9                    py34_0  
astropy                   1.0.3                np19py34_0  
babel                     1.3                      py34_0  
bcolz                     0.9.0                np19py34_0  
beautiful-soup            4.3.2                    py34_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.11.0                   py34_0  
bitarray                  0.8.1                    py34_0  
blaze                     0.8.0                     <pip>
blaze-core                0.8.0                np19py34_0  
blz                       0.6.2                np19py34_1  
bokeh                     0.9.0                np19py34_0  
boto                      2.38.0                   py34_0  
bottleneck                1.0.0                np19py34_0  
certifi                   14.05.14                 py34_0  
cffi                      1.1.0                    py34_0  
clyent                    0.3.4                    py34_0  
colorama                  0.3.3                    py34_0  
configobj                 5.0.6                    py34_0  
cryptography              0.9.1                    py34_0  
curl                      7.43.0                        0  
cython                    0.22.1                   py34_0  
cytoolz                   0.7.3                    py34_0  
datashape                 0.4.5                np19py34_0  
decorator                 4.0.2                    py34_0  
docutils                  0.12                     py34_0  
dynd-python               0.6.5                np19py34_0  
enum34                    1.0.4                    py33_0  
fastcache                 1.0.2                    py34_0  
flask                     0.10.1                   py34_1  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
greenlet                  0.4.7                    py34_0  
h5py                      2.5.0                np19py34_3  
hdf5                      1.8.15.1                      1  
idna                      2.0                      py34_0  
ipykernel                 4.0.3                    py34_0  
ipython                   4.0.0                    py34_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          3.2.0                    py34_0  
ipython-qtconsole         3.2.0                    py34_0  
ipython_genutils          0.1.0                    py34_0  
ipywidgets                4.0.2                    py34_0  
itsdangerous              0.24                     py34_0  
jdcal                     1.0                      py34_0  
jedi                      0.8.1                    py34_0  
jinja2                    2.8                      py34_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
jupyter                   1.0.0                    py34_0  
jupyter-client            4.0.0                     <pip>
jupyter-console           4.0.0                     <pip>
jupyter-core              4.0.4                     <pip>
jupyter_client            4.0.0                    py34_0  
jupyter_console           4.0.0                    py34_0  
jupyter_core              4.0.4                    py34_0  
libdynd                   0.6.5                         0  
libffi                    3.0.13                        0  
libgfortran               1.0                           0  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.5.0                    py34_0  
lxml                      3.4.4                    py34_0  
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_2  
mistune                   0.7                      py34_0  
mock                      1.0.1                    py34_0  
multipledispatch          0.4.7                    py34_0  
nbconvert                 4.0.0                    py34_0  
nbformat                  4.0.0                    py34_0  
networkx                  1.9.1                    py34_0  
nltk                      3.0.3                np19py34_0  
nose                      1.3.7                    py34_0  
notebook                  4.0.2                    py34_0  
numba                     0.19.1               np19py34_0  
numexpr                   2.4.3                np19py34_0  
numpy                     1.9.2                    py34_1  
odo                       0.3.2                np19py34_0  
openblas                  0.2.14                        1  
openpyxl                  1.8.5                    py34_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py34_0  
path.py                   7.6                      py34_0  
patsy                     0.3.0                np19py34_0  
pep8                      1.6.2                    py34_0  
pexpect                   3.3                      py34_0  
pickleshare               0.5                      py34_0  
pillow                    2.8.2                    py34_0  
pip                       7.1.0                    py34_1  
ply                       3.6                      py34_0  
psutil                    2.2.1                    py34_0  
ptyprocess                0.4                      py34_0  
py                        1.4.27                   py34_0  
pyasn1                    0.1.7                    py34_0  
pycosat                   0.6.1                    py34_0  
pycparser                 2.14                     py34_0  
pycrypto                  2.6.1                    py34_0  
pycurl                    7.19.5.1                 py34_2  
pyflakes                  0.9.2                    py34_0  
pygments                  2.0.2                    py34_0  
pyopenssl                 0.15.1                   py34_1  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.3                   py34_1  
pytables                  3.2.0                np19py34_0  
pytest                    2.7.1                    py34_0  
python                    3.4.3                         1  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.4                   py34_0  
pyyaml                    3.11                     py34_1  
pyzmq                     14.7.0                   py34_0  
qt                        4.8.6                         3  
qtconsole                 4.0.1                    py34_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py34_0  
requests                  2.7.0                    py34_0  
rope                      0.9.4                    py34_1  
rope-py3k-0.9.4           1                         <pip>
runipy                    0.1.3                    py34_0  
scikit-image              0.11.3               np19py34_0  
scikit-learn              0.16.1               np19py34_0  
scipy                     0.16.0               np19py34_1  
seaborn                   0.6.0                np19py33_0  
setuptools                18.1                     py34_0  
simplegeneric             0.8.1                    py34_0  
sip                       4.16.5                   py34_0  
six                       1.9.0                    py34_0  
snowballstemmer           1.2.0                    py34_0  
sockjs-tornado            1.0.1                    py34_0  
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
spyder                    2.3.5.2                  py34_0  
spyder-app                2.3.5.2                  py34_0  
sqlalchemy                1.0.5                    py34_0  
sqlite                    3.8.4.1                       1  
statsmodels               0.6.1                np19py34_0  
sympy                     0.7.6                    py34_0  
system                    5.8                           2  
tables                    3.2.0                     <pip>
terminado                 0.5                      py34_0  
theano                    0.7.0                np19py34_0  
tk                        8.5.18                        0  
toolz                     0.7.2                    py34_0  
tornado                   4.2.1                    py34_0  
traitlets                 4.0.0                    py34_0  
ujson                     1.33                     py34_0  
util-linux                2.21                          0  
werkzeug                  0.10.4                   py34_0  
wheel                     0.24.0                   py34_0  
xlrd                      0.9.3                    py34_0  
xlsxwriter                0.7.3                    py34_0  
xlwt                      1.0.0                    py34_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
